name: Polybot Build Dev

on:
  push:
    branches:
      - dev
#
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image-docker.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        id: build-image-docker
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

          IMAGE_TAG="polybot-dev:${{ github.run_number }}"
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

          docker build --push -t yazanyehya/$IMAGE_TAG .

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      image: ${{ needs.Build.outputs.image }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEV_EC2_HOST: ${{ secrets.DEV_EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
      BOT_APP_URL: ${{secrets.BOT_APP_URL}}
      AWS_S3_BUCKET_DEV: ${{secrets.AWS_S3_BUCKET_DEV}}
      BOT_APP_CERT_PATH: ${{secrets.BOT_APP_CERT_PATH}}
      YOLO_URL: ${{secrets.YOLO_URL}}
      SQS_QUEUE_URL: ${{secrets.SQS_QUEUE_URL}}
