name: Polybot Build Dev

on:
  push:
    branches:
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-output.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Set image tag
        id: set-output
        run: |
          IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/polybot-dev:${{ github.run_number }}"
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ steps.set-output.outputs.image }} .
          docker push ${{ steps.set-output.outputs.image }}

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      image: ${{ needs.Build.outputs.image }}
