name: Simple CI Test

on:
  pull_request:
    branches:
      - main

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "✅ Workflow ran successfully!"
