name: Docker Scout Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  docker-scout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Build Docker image
      run: |
        docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/polybot-scout:${{ github.sha }} .
    - name: Run Docker Scout scan
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ secrets.DOCKERHUB_USERNAME }}/polybot-scout:${{ github.sha }}
        only-severities: critical,high
        exit-code: 1
        summary: true
        write-comment: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        format: json